baseURL = 'https://anhthinguyen2644.github.io/MyMainBlog/'
publishDir = "docs"
languageCode = 'vi'
title = '‚ùâAnh Thi BLOG‚ùâ'
theme = "PaperMod"

[params]
    env = "production"
    title = "Blog ƒê·ªì √Ån - Nguy·ªÖn Qu·ª≥nh Anh Thi"
    defaultTheme = "auto"
    
    [params.assets]
        favicon = "/icon.png"
        favicon16x16 = "/icon.png"
        favicon32x32 = "/icon.png"
        apple_touch_icon = "/icon.png"
    
    # --- C√ÅC T√çNH NƒÇNG GIAO DI·ªÜN ---
    ShowCodeCopyButtons = true
    ShowReadingTime = true
    ShowShareButtons = true
    ShowToc = true
    ShowBreadCrumbs = true

    [params.toc]
        open = true

# --- MENU ---
[[menu.main]]
    identifier = "posts"
    name = "üìñ Danh s√°ch B√†i vi·∫øt" 
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "about"
    name = "Gi·ªõi thi·ªáu"
    url = "/about/"
    weight = 20

[[menu.main]]
    identifier = "cong-nghe-xin"
    name = "C√¥ng ngh·ªá x·ªãn"
    url = "/cong-nghe-xin/"
    weight = 30

[[menu.main]]
    identifier = "tags"
    name = "üè∑Ô∏è Ch·ªß ƒë·ªÅ"
    url = "/tags/"
    weight = 40


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true