baseURL = 'https://anhthinguyen2644.github.io/Bloglaptrinh/'
publishDir = "docs"
languageCode = 'vi'
title = '‚ùâAnh Thi BLOG‚ùâ'
theme = "PaperMod"

[params]
    env = "production"
    title = "Blog ƒê·ªì √Ån - Nguy·ªÖn Qu·ª≥nh Anh Thi"
    defaultTheme = "auto"
    
    [params.assets]
        favicon = "/icon.png"
        favicon16x16 = "/icon.png"
        favicon32x32 = "/icon.png"
        apple_touch_icon = "/icon.png"
    
    # --- C√ÅC T√çNH NƒÇNG GIAO DI·ªÜN ---
    ShowCodeCopyButtons = true
    ShowReadingTime = true
    ShowShareButtons = true
    ShowToc = true
    ShowBreadCrumbs = true

    [params.toc]
        open = true

    [params.homeInfoParams]
        Title = "Ch√†o m·ª´ng b·∫°n ƒë·∫øn v·ªõi Blog c√° nh√¢n c·ªßa Thi ! üëã"
        Content = "N∆°i chia s·∫ª b√†i vi·∫øt v·ªÅ Java, JavaScript v√† C√¥ng ngh·ªá m·ªõi ph·ª•c v·ª• h·ªçc ph·∫ßn L·∫≠p tr√¨nh m·∫°ng."

    

[[menu.main]]
    identifier = "posts"
    name = "B√†i vi·∫øt"
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "about"
    name = "Gi·ªõi thi·ªáu"
    url = "/about/"
    weight = 20

[[menu.main]]
    identifier = "cong-nghe-xin"
    name = "C√¥ng ngh·ªá x·ªãn"
    url = "/cong-nghe-xin/"
    weight = 30

[[menu.main]]
    identifier = "tags"
    name = "üè∑Ô∏è Ch·ªß ƒë·ªÅ"
    url = "/tags/"
    weight = 40